# Multiple imputation by chained equations (MICE)

In [1]:
# Cargar bibliotecas
import seaborn as sns
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [2]:
# Cargar el dataset de Titanic desde seaborn
titanic = sns.load_dataset('titanic')

In [3]:
# Mostrar primeros valores
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# Check missing data
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
# Vamos a imputar los valores faltantes de la columna 'age' (edad)
# Seleccionamos un subconjunto de columnas para el ejemplo
data = titanic[['age', 'fare', 'pclass', 'sex']]

# Convertimos las variables categóricas en variables dummy (la variable 'sex' es categórica)
data = pd.get_dummies(data, drop_first=True)

data.head(20)

     age     fare  pclass  sex_male
0   22.0   7.2500       3      True
1   38.0  71.2833       1     False
2   26.0   7.9250       3     False
3   35.0  53.1000       1     False
4   35.0   8.0500       3      True
5    NaN   8.4583       3      True
6   54.0  51.8625       1      True
7    2.0  21.0750       3      True
8   27.0  11.1333       3     False
9   14.0  30.0708       2     False
10   4.0  16.7000       3     False
11  58.0  26.5500       1     False
12  20.0   8.0500       3      True
13  39.0  31.2750       3      True
14  14.0   7.8542       3     False
15  55.0  16.0000       2     False
16   2.0  29.1250       3      True
17   NaN  13.0000       2      True
18  31.0  18.0000       3     False
19   NaN   7.2250       3     False

In [6]:
# Crear el imputador MICE (IterativeImputer)
imputer = IterativeImputer(max_iter=10, random_state=0)

In [7]:
# Imputar los valores faltantes
data_imputed = pd.DataFrame(imputer.fit_transform(data), columns=data.columns)

In [8]:
# Mostrar los datos originales con valores faltantes
print("Datos originales (con valores faltantes):")
data.head(30)

Datos originales (con valores faltantes):

     age      fare  pclass  sex_male
0   22.0    7.2500       3      True
1   38.0   71.2833       1     False
2   26.0    7.9250       3     False
3   35.0   53.1000       1     False
4   35.0    8.0500       3      True
5    NaN    8.4583       3      True
6   54.0   51.8625       1      True
7    2.0   21.0750       3      True
8   27.0   11.1333       3     False
9   14.0   30.0708       2     False
10   4.0   16.7000       3     False
11  58.0   26.5500       1     False
12  20.0    8.0500       3      True
13  39.0   31.2750       3      True
14  14.0    7.8542       3     False
15  55.0   16.0000       2     False
16   2.0   29.1250       3      True
17   NaN   13.0000       2      True
18  31.0   18.0000       3     False
19   NaN    7.2250       3     False
20  35.0   26.0000       2      True
21  34.0   13.0000       2      True
22  15.0    8.0292       3     False
23  28.0   35.5000       1      True
24   8.0   21.0750       3     False
25  38.0   31.3875       3     False
26   NaN    7.2250       3      True
27  19.0  263.0000       1      True
28   NaN    7.8792       3     False
29   NaN    7.8958       3      True

In [9]:
# Mostrar los datos después de la imputación múltiple (MICE)
print("\nDatos después de la imputación múltiple (MICE):")
data_imputed.head(30)

Datos después de la imputación múltiple (MICE):

          age      fare  pclass  sex_male
0   22.000000    7.2500     3.0       1.0
1   38.000000   71.2833     1.0       0.0
2   26.000000    7.9250     3.0       0.0
3   35.000000   53.1000     1.0       0.0
4   35.000000    8.0500     3.0       1.0
5   26.082704    8.4583     3.0       1.0
6   54.000000   51.8625     1.0       1.0
7    2.000000   21.0750     3.0       1.0
8   27.000000   11.1333     3.0       0.0
9   14.000000   30.0708     2.0       0.0
10   4.000000   16.7000     3.0       0.0
11  58.000000   26.5500     1.0       0.0
12  20.000000    8.0500     3.0       1.0
13  39.000000   31.2750     3.0       1.0
14  14.000000    7.8542     3.0       0.0
15  55.000000   16.0000     2.0       0.0
16   2.000000   29.1250     3.0       1.0
17  33.850204   13.0000     2.0       1.0
18  31.000000   18.0000     3.0       0.0
19  22.070708    7.2250     3.0       0.0
20  35.000000   26.0000     2.0       1.0
21  34.000000   13.0000     2.0       1.0
22  15.000000    8.0292     3.0       0.0
23  28.000000   35.5000     1.0       1.0
24   8.000000   21.0750     3.0       0.0
25  38.000000   31.3875     3.0       0.0
26  26.127637    7.2250     3.0       1.0
27  19.000000  263.0000     1.0       1.0
28  22.046873    7.8792     3.0       0.0
29  26.103198    7.8958     3.0       1.0

# Exercise 1
Use MICE on the life-expectancy dataset to fill in missing values.
https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who

In [13]:
# Exercise 1: Load life-expectancy dataset and apply MICE
import pandas as pd
from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.impute import IterativeImputer

# Load the life expectancy dataset
life_expectancy = pd.read_csv('Life Expectancy Data.csv')  # Update with correct path if needed

# Display missing data
print("Missing values in Life Expectancy Dataset:")
print(life_expectancy.isnull().sum())

# Separate numeric columns for imputation and keep non-numeric columns
numeric_columns = life_expectancy.select_dtypes(include=['float64', 'int64']).columns
non_numeric_columns = life_expectancy.select_dtypes(exclude=['float64', 'int64'])

# Apply MICE on the numeric columns only
life_expectancy_numeric = life_expectancy[numeric_columns]
mice_imputer = IterativeImputer(random_state=0)
life_expectancy_imputed_numeric = pd.DataFrame(mice_imputer.fit_transform(life_expectancy_numeric), columns=numeric_columns)

# Combine the imputed numeric data with the non-numeric columns
life_expectancy_imputed = pd.concat([non_numeric_columns.reset_index(drop=True), life_expectancy_imputed_numeric], axis=1)

# Verify imputation results
print("Missing values after MICE imputation:")
print(life_expectancy_imputed.isnull().sum())

# Display the first few rows of the imputed data
life_expectancy_imputed.head()

Missing values in Life Expectancy Dataset:
Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64
Missing values after MICE imputation:
Country                            0
Status                             0
Year                               0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

,Country,Status,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,Developing,2015.0,65.0,263.0,62.0,0.01,71.279624,65.0,1154.0,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,Developing,2014.0,59.9,271.0,64.0,0.01,73.523582,62.0,492.0,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,Developing,2013.0,59.9,268.0,66.0,0.01,73.219243,64.0,430.0,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,Developing,2012.0,59.5,272.0,69.0,0.01,78.184215,67.0,2787.0,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,Developing,2011.0,59.2,275.0,71.0,0.01,7.097109,68.0,3013.0,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

# Exercise 2
Use MICE on the Planets (seaborn) dataset to fill in missing values.

In [12]:

# Exercise 2: Apply MICE to the Planets dataset
import seaborn as sns

# Load planets dataset
planets = sns.load_dataset('planets')

# Display missing data
print("Missing values in Planets Dataset:")
print(planets.isnull().sum())

# Applying MICE to fill in missing values
planets_imputed = pd.DataFrame(mice_imputer.fit_transform(planets.select_dtypes(include=['float64', 'int64'])),
                               columns=planets.select_dtypes(include=['float64', 'int64']).columns)

# Verify imputation results
print("Missing values after MICE imputation:")
print(planets_imputed.isnull().sum())
planets_imputed.head()

Missing values in Planets Dataset:
method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64
Missing values after MICE imputation:
number            0
orbital_period    0
mass              0
distance          0
year              0
dtype: int64

   number  orbital_period   mass  distance    year
0     1.0         269.300   7.10     77.40  2006.0
1     1.0         874.774   2.21     56.95  2008.0
2     1.0         763.000   2.60     19.84  2011.0
3     1.0         326.030  19.40    110.62  2007.0
4     1.0         516.220  10.50    119.47  2009.0